### ISSUE TITLE
Add contents in Readme.md

### ISSUE THREAD

**Issue by rohansx** [rohansx/web3-security#1]
Add contents for installation and running on the local host.
here's the step  
- clone 
- install mdbook in the system
- "mdbook serve --open" this is the command to run on terminal to serve the application on localhost 

Refer other readme.md file and make according to that

**Comment by johnweslee** [comment]
Hi @rohansx, i would like to contribute to this.

**Comment by SyedTathahir** [comment]
Hey @rohansx , i would also like to contribute to this

**Comment by Technobromo** [comment]
Hey @rohansx here is your readme.md 

[https://technobromo.com/index.php/s/r9xTDN688NESrJP](https://technobromo.com/index.php/s/r9xTDN688NESrJP)

[https://drive.google.com/file/d/1ke3Gg6F8Rc05UDHtunJo7f9wSQ25WI_l/view?usp=sharing](https://drive.google.com/file/d/1ke3Gg6F8Rc05UDHtunJo7f9wSQ25WI_l/view?usp=sharing)

I am really glad to help and contribute to this project , Feel free to ask for any amendments in the readme.md

**Comment by Technobromo** [comment]
You use this google drive link if the above dosen't work  

[https://drive.google.com/file/d/1ke3Gg6F8Rc05UDHtunJo7f9wSQ25WI_l/view?usp=sharing](https://drive.google.com/file/d/1ke3Gg6F8Rc05UDHtunJo7f9wSQ25WI_l/view?usp=sharing)

**Comment by rohansx** [comment]
@johnweslee check the readme file again it has been added, but there is no brief description about it and also add the repository link, feel free to modify it according to you

**Comment by rohansx** [comment]
@SyedTathahir  @Technobromo  thank you for asking, you can check the project and add your issue according to you i'll assign you that task

**Comment by rohansx** [comment]
Thanks @johnweslee
